version: "3.4"

services:
  db:
    build: db
    ports:
      - 1433:1433
    healthcheck:
      test: "exit 0"

  py-srv:
    build:
      context: py-srv
    ports:
      - 80:5000
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:1433
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=120
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"

  py-test-srv:
    build:
      context: py-test-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:1433,py-srv:5000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=120
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - py-srv
    links:
      - "py-srv:py-srv"
